apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: vaultwarden
  namespace: argocd
  labels:
    name: vaultwarden
spec:
  project: authentication
  sources:
    - repoURL: https://charts.gabe565.com
      targetRevision: 0.10.1
      chart: vaultwarden
      helm:
        valueFiles:
          - $values/apps/authentication/values/vaultwarden/values.yaml
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      ref: values
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      path: apps/authentication/values/vaultwarden/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  info:
    - name: 'vaultwarden:'
      value: 'https://example.com'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 1
