apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
    - "victor.io"
  gateways:
    - istio-system/gateway
  http:
    - match:
        - uri:
            prefix: /keycloak
      route:
        - destination:
            port:
              number: 80
            host: authentication-keycloak