apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
    - grafana.victor.internal
  gateways:
    - istio-system/gateway
  http:
    - name: "grafana"
      route:
        - destination:
            host: grafana-grafana-operator-grafana-service