apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: base
  namespace: argocd
  labels:
    name: base
spec:
  project: authentication
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.18.2
      chart: base
      helm:
        valueFiles:
          - $values/auth/values/base/values.yaml
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
#      ref: values
#    - repoURL: https://github.com/victorbiga/argocd-authentication.git
#      targetRevision: master
#      path: auth/values/base/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  info:
    - name: 'Example:'
      value: 'https://example.com'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jqPathExpressions:
        - '.webhooks[].failurePolicy'
  revisionHistoryLimit: 1