apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: cert-manager
  namespace: argocd
  labels:
    name: cert-manager
spec:
  project: authentication
  sources:
  - repoURL: https://charts.jetstack.io
    targetRevision: 1.12.3
    chart: cert-manager
    helm:
      valueFiles:
      - $values/auth/values/values-cert-manager.yaml
  - repoURL: https://github.com/victorbiga/argocd-authentication.git
    targetRevision: master
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  info:
    - name: 'Example:'
      value: 'https://example.com'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 1