apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: istiod
  namespace: argocd
  labels:
    name: istiod
spec:
  project: authentication
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.18.2
      chart: istiod
      helm:
        valueFiles:
          - $values/auth/values/istiod/values.yaml
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
#      ref: values
#    - repoURL: https://github.com/victorbiga/argocd-authentication.git
#      targetRevision: master
#      path: auth/values/istiod/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  info:
    - name: 'Example:'
      value: 'https://example.com'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 1