---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jaeger
spec:
  hosts:
    - jaeger.victor.internal
  gateways:
    - istio-system/gateway
  http:
    - name: "jaeger"
      route:
        - destination:
            host: jaeger
---
