---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
spec:
  hosts:
    - kiali.victor.internal
  gateways:
    - istio-system/gateway
  http:
    - name: "kiali"
      route:
        - destination:
            host: kiali-server
---
