apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vaultwarden
spec:
  hosts:
    - vaultwarden.victor.internal
  gateways:
    - istio-system/gateway
  http:
    - name: "vaultwarden"
      route:
        - destination:
            host: vaultwarden