apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  name: grafana
  namespace: argocd
  labels:
    name: grafana
spec:
  project: observability
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 3.3.1
      chart: grafana-operator
      helm:
        valueFiles:
          - $values/apps/observability/values/grafana/values.yaml
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      ref: values
#    - repoURL: https://github.com/victorbiga/argocd-authentication.git
#      targetRevision: master
#      path: apps/authentication/values/grafana/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  info:
    - name: 'Grafana:'
      value: 'http://victor.internal/grafana'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 1
