apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "13"
  name: jaeger
  namespace: argocd
  labels:
    name: jaeger
spec:
  project: observability
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 0.71.14
      chart: jaeger
      helm:
        valueFiles:
          - $values/apps/observability/values/jaeger/values.yaml
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      ref: values
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      path: apps/observability/values/jaeger/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: jaeger
  info:
    - name: 'Jaeger:'
      value: 'http://jaeger.victor.internal'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 1
