apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  name: kiali
  namespace: argocd
  labels:
    name: kiali
spec:
  project: observability
  sources:
    - repoURL: https://kiali.org/helm-charts
      targetRevision: 1.72.0
      chart: kiali-server
      helm:
        valueFiles:
          - $values/apps/observability/values/kiali/values.yaml
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      ref: values
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      path: apps/observability/values/kiali/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali
  info:
    - name: 'kiali:'
      value: 'http://kiali.victor.internal'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 1
