apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  name: prometheus
  namespace: argocd
  labels:
    name: prometheus
spec:
  project: observability
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 23.4.0
      chart: prometheus
      helm:
        valueFiles:
          - $values/apps/observability/values/prometheus/values.yaml
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      ref: values
    - repoURL: https://github.com/victorbiga/argocd-authentication.git
      targetRevision: master
      path: apps/observability/values/prometheus/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  info:
    - name: 'prometheus:'
      value: 'http://prometheus.victor.internal'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 1
