apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  servers:
    - hosts:
        - victor.internal
      port:
        name: http
        number: 80
        protocol: HTTP