---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
spec:
  hosts:
    - prometheus.victor.internal
  gateways:
    - istio-system/gateway
  http:
    - name: "prometheus"
      route:
        - destination:
            host: prometheus-server
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: alertmanager
spec:
  hosts:
    - alertmanager.victor.internal
  gateways:
    - istio-system/gateway
  http:
    - name: "alertmanager"
      route:
        - destination:
            host: prometheus-alertmanager
---